# Generated by Django 5.2.3 on 2025-06-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_num',
            field=models.CharField(default='8921245881', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
